name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION_LABEL: v-${{ github.run_number }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0' # Specific Node.js version for consistency

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci # Use npm ci for cleaner installs

      - name: Build the application
        run: npm run build

      - name: Clean up unnecessary files
        run: |
          rm -rf src tests # Remove source and test files
          find . -name "*.ts" -type f -delete # Remove TypeScript files

      - name: Generate deployment package
        run: |
          zip -r deploy.zip dist/ node_modules/ package.json package-lock.json Procfile
          ls -la

      - name: Verify deployment package
        run: unzip -l deploy.zip # List contents of zip for verification

      - name: Validate environment variables
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ] || [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ] || [ -z "${{ secrets.AWS_REGION }}" ]; then
            echo "Missing required AWS secrets"
            exit 1
          fi

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: nestjs-app
          environment_name: nestjs-app-env
          version_label: ${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip